const PRODUCT_VARIATION_KEYS: readonly string[] = [
  "actual_remain_quantity",
  "average_imported_price",
  "barcode",
  "batch_position",
  "bonus_products",
  "bonus_variations",
  "brand_id",
  "categories",
  "component",
  "component_id",
  "composite_products",
  "data",
  "display_id",
  "fields",
  "id",
  "image",
  "images",
  "inserted_at",
  "is_composite",
  "is_hidden",
  "is_locked",
  "is_published",
  "is_removed",
  "is_sell_negative_variation",
  "keyValue",
  "keyword",
  "last_imported_price",
  "manipulation_warehouses",
  "measure_group_id",
  "measure_info",
  "name",
  "note",
  "note_product",
  "page_number",
  "page_size",
  "pending_quantity",
  "price_at_counter",
  "product",
  "product_attributes",
  "product_id",
  "quantity",
  "remain_quantity",
  "retail_price",
  "retail_price_after_discount",
  "returning_quantity",
  "selling_avg",
  "shelf_position",
  "shop_id",
  "size",
  "success",
  "supplier_product_ids",
  "tags",
  "total_entries",
  "total_pages",
  "total_purchase_price",
  "total_quantity",
  "updated_at",
  "value",
  "values",
  "variation_id",
  "variations_warehouses",
  "videos",
  "waiting_quantity",
  "warehouse_id",
  "weight",
  "wholesale_price",
];

const WAREHOUSE_KEYS: readonly string[] = [
  "address",
  "affiliate_shop_id",
  "allow_create_order",
  "batch_config",
  "commune_id",
  "country_code",
  "custom_batch_config",
  "custom_id",
  "custom_shelf_config",
  "data",
  "district_id",
  "full_address",
  "hide_config_batch_shelf",
  "id",
  "name",
  "phone_number",
  "postcode",
  "province_id",
  "shelf_config",
  "success",
];

export const REVIEWED_PANCAKE_CONTRACT_KEYS = {
  productVariations: PRODUCT_VARIATION_KEYS,
  warehouses: WAREHOUSE_KEYS,
} as const;

export function assertReviewedPancakeContractKeysConfigured(): void {
  if (
    REVIEWED_PANCAKE_CONTRACT_KEYS.productVariations.length === 0 ||
    REVIEWED_PANCAKE_CONTRACT_KEYS.warehouses.length === 0
  ) {
    throw new Error("Reviewed Pancake contract field allowlists are not configured");
  }
}
